// Generated by gencpp from file saturn_msgs/Control.msg
// DO NOT EDIT!


#ifndef SATURN_MSGS_MESSAGE_CONTROL_H
#define SATURN_MSGS_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace saturn_msgs
{
template <class ContainerAllocator>
struct Control_
{
  typedef Control_<ContainerAllocator> Type;

  Control_()
    : header()
    , u_accel(0.0)
    , u_yawrate(0.0)  {
    }
  Control_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , u_accel(0.0)
    , u_yawrate(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _u_accel_type;
  _u_accel_type u_accel;

   typedef double _u_yawrate_type;
  _u_yawrate_type u_yawrate;





  typedef boost::shared_ptr< ::saturn_msgs::Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::saturn_msgs::Control_<ContainerAllocator> const> ConstPtr;

}; // struct Control_

typedef ::saturn_msgs::Control_<std::allocator<void> > Control;

typedef boost::shared_ptr< ::saturn_msgs::Control > ControlPtr;
typedef boost::shared_ptr< ::saturn_msgs::Control const> ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::saturn_msgs::Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::saturn_msgs::Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::saturn_msgs::Control_<ContainerAllocator1> & lhs, const ::saturn_msgs::Control_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.u_accel == rhs.u_accel &&
    lhs.u_yawrate == rhs.u_yawrate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::saturn_msgs::Control_<ContainerAllocator1> & lhs, const ::saturn_msgs::Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace saturn_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::saturn_msgs::Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::saturn_msgs::Control_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::saturn_msgs::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::saturn_msgs::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::saturn_msgs::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::saturn_msgs::Control_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::saturn_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f42f5551e89d8349e570aae4222e3836";
  }

  static const char* value(const ::saturn_msgs::Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf42f5551e89d8349ULL;
  static const uint64_t static_value2 = 0xe570aae4222e3836ULL;
};

template<class ContainerAllocator>
struct DataType< ::saturn_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "saturn_msgs/Control";
  }

  static const char* value(const ::saturn_msgs::Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::saturn_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float64 u_accel\n"
"float64 u_yawrate\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::saturn_msgs::Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::saturn_msgs::Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.u_accel);
      stream.next(m.u_yawrate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::saturn_msgs::Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::saturn_msgs::Control_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "u_accel: ";
    Printer<double>::stream(s, indent + "  ", v.u_accel);
    s << indent << "u_yawrate: ";
    Printer<double>::stream(s, indent + "  ", v.u_yawrate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SATURN_MSGS_MESSAGE_CONTROL_H
