// Generated by gencpp from file saturn_msgs/ControlArray.msg
// DO NOT EDIT!


#ifndef SATURN_MSGS_MESSAGE_CONTROLARRAY_H
#define SATURN_MSGS_MESSAGE_CONTROLARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <saturn_msgs/Control.h>

namespace saturn_msgs
{
template <class ContainerAllocator>
struct ControlArray_
{
  typedef ControlArray_<ContainerAllocator> Type;

  ControlArray_()
    : header()
    , control_lst()  {
    }
  ControlArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , control_lst(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::saturn_msgs::Control_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::saturn_msgs::Control_<ContainerAllocator> >> _control_lst_type;
  _control_lst_type control_lst;





  typedef boost::shared_ptr< ::saturn_msgs::ControlArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::saturn_msgs::ControlArray_<ContainerAllocator> const> ConstPtr;

}; // struct ControlArray_

typedef ::saturn_msgs::ControlArray_<std::allocator<void> > ControlArray;

typedef boost::shared_ptr< ::saturn_msgs::ControlArray > ControlArrayPtr;
typedef boost::shared_ptr< ::saturn_msgs::ControlArray const> ControlArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::saturn_msgs::ControlArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::saturn_msgs::ControlArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::saturn_msgs::ControlArray_<ContainerAllocator1> & lhs, const ::saturn_msgs::ControlArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.control_lst == rhs.control_lst;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::saturn_msgs::ControlArray_<ContainerAllocator1> & lhs, const ::saturn_msgs::ControlArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace saturn_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::saturn_msgs::ControlArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::saturn_msgs::ControlArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::saturn_msgs::ControlArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::saturn_msgs::ControlArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::saturn_msgs::ControlArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::saturn_msgs::ControlArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::saturn_msgs::ControlArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26a69d081791f88c3703af6f5549edf4";
  }

  static const char* value(const ::saturn_msgs::ControlArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26a69d081791f88cULL;
  static const uint64_t static_value2 = 0x3703af6f5549edf4ULL;
};

template<class ContainerAllocator>
struct DataType< ::saturn_msgs::ControlArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "saturn_msgs/ControlArray";
  }

  static const char* value(const ::saturn_msgs::ControlArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::saturn_msgs::ControlArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"Control[] control_lst\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: saturn_msgs/Control\n"
"std_msgs/Header header\n"
"\n"
"float64 u_accel\n"
"float64 u_yawrate\n"
;
  }

  static const char* value(const ::saturn_msgs::ControlArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::saturn_msgs::ControlArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.control_lst);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::saturn_msgs::ControlArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::saturn_msgs::ControlArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "control_lst[]" << std::endl;
    for (size_t i = 0; i < v.control_lst.size(); ++i)
    {
      s << indent << "  control_lst[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::saturn_msgs::Control_<ContainerAllocator> >::stream(s, indent + "    ", v.control_lst[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SATURN_MSGS_MESSAGE_CONTROLARRAY_H
