// Generated by gencpp from file saturn_msgs/ObstacleStateArray.msg
// DO NOT EDIT!


#ifndef SATURN_MSGS_MESSAGE_OBSTACLESTATEARRAY_H
#define SATURN_MSGS_MESSAGE_OBSTACLESTATEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <saturn_msgs/ObstacleState.h>

namespace saturn_msgs
{
template <class ContainerAllocator>
struct ObstacleStateArray_
{
  typedef ObstacleStateArray_<ContainerAllocator> Type;

  ObstacleStateArray_()
    : header()
    , obstacles()  {
    }
  ObstacleStateArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::saturn_msgs::ObstacleState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::saturn_msgs::ObstacleState_<ContainerAllocator> >> _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleStateArray_

typedef ::saturn_msgs::ObstacleStateArray_<std::allocator<void> > ObstacleStateArray;

typedef boost::shared_ptr< ::saturn_msgs::ObstacleStateArray > ObstacleStateArrayPtr;
typedef boost::shared_ptr< ::saturn_msgs::ObstacleStateArray const> ObstacleStateArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::saturn_msgs::ObstacleStateArray_<ContainerAllocator1> & lhs, const ::saturn_msgs::ObstacleStateArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.obstacles == rhs.obstacles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::saturn_msgs::ObstacleStateArray_<ContainerAllocator1> & lhs, const ::saturn_msgs::ObstacleStateArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace saturn_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c25d44797a7f0424f6e9ee3a9b560ae5";
  }

  static const char* value(const ::saturn_msgs::ObstacleStateArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc25d44797a7f0424ULL;
  static const uint64_t static_value2 = 0xf6e9ee3a9b560ae5ULL;
};

template<class ContainerAllocator>
struct DataType< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "saturn_msgs/ObstacleStateArray";
  }

  static const char* value(const ::saturn_msgs::ObstacleStateArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"ObstacleState[] obstacles\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: saturn_msgs/ObstacleState\n"
"std_msgs/Header header\n"
"\n"
"int32 id\n"
"string name\n"
"StateLite[] predicted_states\n"
"\n"
"================================================================================\n"
"MSG: saturn_msgs/StateLite\n"
"std_msgs/Header header\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"float64 v\n"
"float64 accel\n"
"float64 yawrate\n"
;
  }

  static const char* value(const ::saturn_msgs::ObstacleStateArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleStateArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::saturn_msgs::ObstacleStateArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::saturn_msgs::ObstacleStateArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::saturn_msgs::ObstacleState_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SATURN_MSGS_MESSAGE_OBSTACLESTATEARRAY_H
