// Generated by gencpp from file saturn_msgs/Size.msg
// DO NOT EDIT!


#ifndef SATURN_MSGS_MESSAGE_SIZE_H
#define SATURN_MSGS_MESSAGE_SIZE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace saturn_msgs
{
template <class ContainerAllocator>
struct Size_
{
  typedef Size_<ContainerAllocator> Type;

  Size_()
    : header()
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , wheel_base(0.0)
    , wheel_track(0.0)  {
    }
  Size_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , wheel_base(0.0)
    , wheel_track(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _length_type;
  _length_type length;

   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;

   typedef double _wheel_base_type;
  _wheel_base_type wheel_base;

   typedef double _wheel_track_type;
  _wheel_track_type wheel_track;





  typedef boost::shared_ptr< ::saturn_msgs::Size_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::saturn_msgs::Size_<ContainerAllocator> const> ConstPtr;

}; // struct Size_

typedef ::saturn_msgs::Size_<std::allocator<void> > Size;

typedef boost::shared_ptr< ::saturn_msgs::Size > SizePtr;
typedef boost::shared_ptr< ::saturn_msgs::Size const> SizeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::saturn_msgs::Size_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::saturn_msgs::Size_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::saturn_msgs::Size_<ContainerAllocator1> & lhs, const ::saturn_msgs::Size_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.length == rhs.length &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.wheel_base == rhs.wheel_base &&
    lhs.wheel_track == rhs.wheel_track;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::saturn_msgs::Size_<ContainerAllocator1> & lhs, const ::saturn_msgs::Size_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace saturn_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::saturn_msgs::Size_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::saturn_msgs::Size_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::saturn_msgs::Size_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::saturn_msgs::Size_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::saturn_msgs::Size_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::saturn_msgs::Size_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::saturn_msgs::Size_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0122303aa1e5e98fff82adf25a489b8a";
  }

  static const char* value(const ::saturn_msgs::Size_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0122303aa1e5e98fULL;
  static const uint64_t static_value2 = 0xff82adf25a489b8aULL;
};

template<class ContainerAllocator>
struct DataType< ::saturn_msgs::Size_<ContainerAllocator> >
{
  static const char* value()
  {
    return "saturn_msgs/Size";
  }

  static const char* value(const ::saturn_msgs::Size_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::saturn_msgs::Size_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float64 length\n"
"float64 width\n"
"float64 height\n"
"float64 wheel_base\n"
"float64 wheel_track\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::saturn_msgs::Size_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::saturn_msgs::Size_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.wheel_base);
      stream.next(m.wheel_track);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Size_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::saturn_msgs::Size_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::saturn_msgs::Size_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "length: ";
    Printer<double>::stream(s, indent + "  ", v.length);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "wheel_base: ";
    Printer<double>::stream(s, indent + "  ", v.wheel_base);
    s << indent << "wheel_track: ";
    Printer<double>::stream(s, indent + "  ", v.wheel_track);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SATURN_MSGS_MESSAGE_SIZE_H
